### ISSUE TITLE
docker-compose up fails with FileNotFoundError

### ISSUE THREAD

**Issue by sshleifer** [Helsinki-NLP/Opus-MT#16]
```bash
docker-compose up
```

Results in a succesful build, but fails on attach with the following traceback:

```
WARNING: Image for service opus-mt was built because it did not already exist. To rebuild this image you must use `docker-compose build` or `docker-compose up --build`.
Creating opus-mt_opus-mt_1 ... done
Attaching to opus-mt_opus-mt_1
opus-mt_1  | Traceback (most recent call last):
opus-mt_1  |   File "server.py", line 150, in <module>
opus-mt_1  |     application = make_app(args)
opus-mt_1  |   File "server.py", line 130, in make_app
opus-mt_1  |     worker_pool = initialize_workers(services)
opus-mt_1  |   File "server.py", line 115, in initialize_workers
opus-mt_1  |     source_lang, target_lang, decoder_config)
opus-mt_1  |   File "server.py", line 26, in __init__
opus-mt_1  |     targetspm=self.service.get('targetspm')
opus-mt_1  |   File "/usr/src/app/content_processor.py", line 17, in __init__
opus-mt_1  |     BPEcodes = open(sourcebpe, 'r', encoding="utf-8")
opus-mt_1  | FileNotFoundError: [Errno 2] No such file or directory: './models/en-es/source.bpe'
opus-mt_opus-mt_1 exited with code 1
```

Any ideas how to fix?

**Comment by sshleifer** [comment]
I guessed and downloaded a model and moved it to en-es and that worked!

**Comment by busyboy77** [comment]
any further steps. I'm getting the same error.
